CREATE SCHEMA IF NOT EXISTS filmoteka;

CREATE TABLE user_profile
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_sub VARCHAR(255) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    created_ts   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_ts   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_user_profile_identity_sub UNIQUE (identity_sub),

    CONSTRAINT uk_user_profile_email UNIQUE (email)
);

CREATE TABLE film_list
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    name       VARCHAR(100) NOT NULL,
    created_ts TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_ts TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT film_list_user_fk FOREIGN KEY (user_id) REFERENCES user_profile (id)
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_film_list_user_name ON film_list (user_id, LOWER(name));

CREATE TABLE film_list_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_list_id BIGINT    NOT NULL,
    film_id      BIGINT    NOT NULL,
    added_ts     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT film_list_item_list_fk FOREIGN KEY (film_list_id) REFERENCES film_list (id)
        ON DELETE CASCADE,

    CONSTRAINT uk_film_list_item_list_film UNIQUE (film_list_id, film_id)
);

CREATE INDEX idx_film_list_item_film_id ON film_list_item (film_id);
